pvc:
  storage: 1Gi
  accessMode: ReadWriteOnce
  annotations:
    helm.sh/resource-policy: "keep"

# ingress
ingress:
  enabled: true
  host: pchclient.local
  tlsEnabled: false
  annotations:

# database
dbHost: postgres
dbPort: 5432
dbName: demo_db
dbUser: demo_user
dbPass: aF1dG2qU5dX1
dbSchema: public

# hasura
hasuraHost: graphql
hasuraPort: 8080
hasuraGui: true
devmode: true
logtypes: "startup, http-log, webhook-log, websocket-log, query-log"

# frontend
webappHost: frontend
webappPort: 80

# services
services:
  postgres:
    image: postgres:12
    replicas: 1
    ports:
      - 5432
  graphql:
    image: hasura/graphql-engine:v1.3.3.cli-migrations
    replicas: 1
    ports:
      - 8080
  frontend:
    image: 
      repository: andreask81/frontend
      frontend_tag: "20211217_126"
    replicas: 1
    ports:
      - 80
  parser:
    image: 
      repository: andreask81/parser
      parser_tag: "20211217_126"
    replicas: 1