apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
{{ include "pch-client.labels" . | indent 4 }}
  name: frontend
{{- with .Values.services.frontend }}
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .image }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 2
      restartPolicy: Always
      {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}